# Generated by Django 3.2.3 on 2021-05-29 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbase',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hospital.medico'),
        ),
        migrations.AddField(
            model_name='hospitalbase',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hospital.patient'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hospital.hospitalbase'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hospital.hospitalbase'),
        ),
    ]
