# Generated by Django 3.2.3 on 2021-05-29 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210528_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalbase',
            name='patient',
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hospital.hospitalbase'),
        ),
    ]
