# Generated by Django 3.2.3 on 2021-05-29 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210528_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalbase',
            name='medico',
        ),
    ]
