# Generated by Django 3.2.3 on 2021-05-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_hospitalbase_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
    ]
