# Generated by Django 3.2.3 on 2021-05-29 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_patient_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.medico'),
        ),
    ]
