# Generated by Django 3.2.3 on 2021-05-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_patient_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_atendimento',
            field=models.BooleanField(default=0),
        ),
    ]
