# Generated by Django 3.2.3 on 2021-05-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_patient_is_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitais', to='hospital.hospitalbase'),
        ),
    ]
