# Generated by Django 3.2.3 on 2021-05-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_medico_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbase',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medico_hospital', to='hospital.medico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_medico', to='hospital.hospitalbase'),
        ),
    ]
